var TLTimelineData = {
	id : 137152,
	storySpacing : 1,

	host : "www.ctrip.com",
	homePage : false,
	showAdBlock : "false",
	
	title : "RELEASE STATUS DASHBOARD",
	urlFriendlyTitle : "RELEASE STATUS DASHBOARD",
	startDate : "1000-04-01 00:00:00",
	endDate : "2020-04-30 00:00:00",
	//introText : "A 3D version of our history of the Tower of London timeline.",
	//introImage : "http://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Tower_of_london_from_swissre.jpg/627px-Tower_of_london_from_swissre.jpg",
	authorName : "Alex Kearns",
	"accountType" : "Sliver",
	//backgroundImage : "/timeline/assets/ui/bg.jpg",
	//introImageCredit : "",
	//backgroundImageCredit : "Image courtesy of Matthias Kabel via WikiMedia Commons",
	feed : "",
	mainColour : "9e9e9e",
	zoom : "decade-small-year",
	initialFocus : "first",
	embedHash : "4308693385",
	embed : "false",
	secret : "false",
	"public" : "yes",
	dontDisplayIntroPanel : 1,
	openReadMoreLinks : 1,
	storyDateStatus : 0,
	
	viewType : 1,
	showTitleBlock : 0,
	backgroundColour : "none",
	"storyDateFormat": "MM-DD HH:mm",//auto
    "topDateFormat": "YYYY-MM-DD HH:mm",//auto
    "sliderDateFormat": "MM-DD HH:mm",//auto
    
	"language": "chinese-simplified",
    "displayStripes": 1,
    "htmlFormatting": 1,
	containerBackgroundColour : "37474f",
	sliderBackgroundColour : "001414",
	sliderTextColour : "808080",
	sliderDetailsColour : "282828",
	sliderDraggerColour : "808080",
	headerBackgroundColour : "263238",
	headerTextColour : "808080",
	showGroupAuthorNames : "1",
	durHeadlineColour : "ffffff",
	cssFile : "",
	altFlickrImageUrl : "",
	fontBase : 'default',
	fontHead : '"Arial Black", "Arial Bold", Gadget, sans-serif;',
	fontBody : 'default',
	lightboxStyle : '0',
	showControls : '1',
	lazyLoading : '1',
	protection : "",
	expander : "2",
	copyable : "0",
	settings3d : "1,ffffff,0.13912,1200,0.2016,1.40833,1,5,1",
	bgStyle : 0,
	bgScale : 100,
	urlHashing : 0,
	categories : [ {
		id : 95716,
		title : "机票",
		colour : "37474f",
		"layout" : "1",
		"rows" : "30",
		"order" : "1",
		"size" : "30"
	}, {
		id : 95717,
		title : "酒店",
		colour : "37474f",
		"layout" : "1",
		"rows" : "18",
		"order" : "2",
		"size" : "18"
	}, {
		id : 95718,
		title : "团队游",
		colour : "37474f",
		"layout" : "1",
		"rows" : "12",
		"order" : "3",
		"size" : "12"
	}, {
		id : 595716,
		title : "金融",
		colour : "37474f",
		"layout" : "1",
		"rows" : "1",
		"order" : "4",
		"size" : "1"
	}, {
		id : 495717,
		title : "公共产品",
		colour : "37474f",
		"layout" : "1",
		"rows" : "1",
		"order" : "5",
		"size" : "1"
	}, {
		id : 395718,
		title : "国际业务",
		colour : "37474f",
		"layout" : "1",
		"rows" : "1",
		"order" : "6",
		"size" : "1"
	}, {
		id : 295716,
		title : "商旅",
		colour : "37474f",
		"layout" : "1",
		"rows" : "1",
		"order" : "7",
		"size" : "1"
	}, {
		id : 195717,
		title : "套餐",
		colour : "37474f",
		"layout" : "1",
		"rows" : "1",
		"order" : "8",
		"size" : "1"
	}, {
		id : 957180,
		title : "地面服务",
		colour : "37474f",
		"layout" : "1",
		"rows" : "1",
		"order" : "9",
		"size" : "1"
	}, {
		id : 957169,
		title : "邮轮",
		colour : "37474f",
		"layout" : "1",
		"rows" : "1",
		"order" : "10",
		"size" : "1"
	}, {
		id : 957178,
		title : "攻略社区",
		colour : "37474f",
		"layout" : "1",
		"rows" : "1",
		"order" : "11",
		"size" : "1"
	}, {
		id : 957187,
		title : "用车",
		colour : "37474f",
		"layout" : "1",
		"rows" : "1",
		"order" : "12",
		"size" : "1"
	}, {
		id : 957166,
		title : "框架",
		colour : "37474f",
		"layout" : "1",
		"rows" : "1",
		"order" : "13",
		"size" : "1"
	}, {
		id : 957175,
		title : "营销",
		colour : "37474f",
		"layout" : "1",
		"rows" : "1",
		"order" : "14",
		"size" : "1"
	}, {
		id : 957184,
		title : "无线",
		colour : "37474f",
		"layout" : "1",
		"rows" : "1",
		"order" : "15",
		"size" : "1"
	}, {
		id : 957163,
		title : "团购",
		colour : "37474f",
		"layout" : "1",
		"rows" : "1",
		"order" : "16",
		"size" : "1"
	}, {
		id : 957172,
		title : "主题游",
		colour : "37474f",
		"layout" : "1",
		"rows" : "1",
		"order" : "17",
		"size" : "1"
	}, {
		id : 957181,
		title : "高铁",
		colour : "37474f",
		"layout" : "1",
		"rows" : "1",
		"order" : "18",
		"size" : "1"
	}],
	feeds : [],
	stories : [
			{
				id : 1320882,
				ownerId : "86389",
				ownerName : "",
				title : "Henry VI (2nd reign)",
				startDate : "1470-04-01 00:00:00",
				endDate : "1471-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597651,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/HenryVIofEngland.JPG/328px-HenryVIofEngland.JPG",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.5",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320883,
				ownerId : "86389",
				ownerName : "",
				title : "Henry VIII",
				startDate : "1509-04-01 00:00:00",
				endDate : "1547-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597652,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Hans_Holbein_d._J._-_Portrait_of_Henry_VIII_-_WGA11558.jpg/322px-Hans_Holbein_d._J._-_Portrait_of_Henry_VIII_-_WGA11558.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320884,
				ownerId : "86389",
				ownerName : "",
				title : "The White Tower Built",
				startDate : "1078-04-01 00:00:00",
				endDate : "1100-04-01 00:00:00",
				text : "The White Tower forms the heart of the Tower of London.",
				fullText : "",
				category : "95718",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/White_Tower_(Tower_of_London)",
				media : [
						{
							id : 597653,
							//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Tower_of_London_White_Tower.jpg/320px-Tower_of_London_White_Tower.jpg",
							caption : "Photo by Bernard Gagnon, from Wikimedia Commons",
							//type : "Image",
							thumbPosition : "0,0",
							externalMediaThumb : "",
							externalMediaType : "",
							externalMediaId : "",
							orderIndex : 1
						},
						{
							id : 597654,
							//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Towrlndn.JPG/424px-Towrlndn.JPG",
							caption : "Illumination showing the White Tower from manuscript of poems by Charles, Duke of Orleans, in the 15th century - the original manuscript is held in the British Library",
							//type : "Image",
							thumbPosition : "0,0",
							externalMediaThumb : "",
							externalMediaType : "",
							externalMediaId : "",
							orderIndex : 2
						} ]
			},
			{
				id : 1320885,
				ownerId : "86389",
				ownerName : "",
				title : "The Tower Founded",
				startDate : "1066-04-01 00:00:00",
				endDate : "1066-04-01 00:00:00",
				text : "The first structures of what would become the Tower of London are built for William the Conqueror. It is believed they were made from timber, and were replaced by the White Tower when it was built.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "",
				media : []
			},
			{
				id : 1320886,
				ownerId : "86389",
				ownerName : "",
				title : "William II",
				startDate : "1087-04-01 00:00:00",
				endDate : "1100-04-01 00:00:00",
				text : "William II was the third son of William I - his elder brother inherited Normandy, whilst William II inherited England. According to his contemporary chroniclers, William II was an unpopular king. He died in a hunting accident in 1100, and left behind no heirs.",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/William_II_of_England",
				media : [ {
					id : 597655,
					//src : "http://upload.wikimedia.org/wikipedia/commons/9/92/William_II_of_England.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.3696",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320887,
				ownerId : "86389",
				ownerName : "",
				title : "William I",
				startDate : "1066-04-01 00:00:00",
				endDate : "1087-04-01 00:00:00",
				text : "Also known as William the Conqueror, William was the cousin of the childless English king Edward the Confessor. It was understood that William had been named as Edward's successor, but Edward named another his successor on his deathbed. William invaded England to claim what he saw as rightly his own, and won.",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/William_the_Conqueror",
				media : [ {
					id : 597656,
					//src : "http://upload.wikimedia.org/wikipedia/commons/3/36/Vilem1.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.6827",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320888,
				ownerId : "86389",
				ownerName : "",
				title : "Henry I",
				startDate : "1100-04-01 00:00:00",
				endDate : "1135-04-01 00:00:00",
				text : "Henry I was the fourth son of William I, and claimed the English throne on his brother William II's death. He invaded Normandy and imprisoned his eldest brother Robert, putting the two territories under a single ruler again. His only legitimate son died, and he planned to make his daughter Matilda and her husband Geoffrey of Anjou successors, but the throne was claimed by his nephew Stephen instead.",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Henry_I_of_England",
				media : [ {
					id : 597657,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Henry1.jpg/295px-Henry1.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.7215",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320889,
				ownerId : "86389",
				ownerName : "",
				title : "Stephen",
				startDate : "1135-04-01 00:00:00",
				endDate : "1154-04-01 00:00:00",
				text : "The nephew of Henry I, Stephen ruled over England during a period of civil war known as the Anarchy. Peace was finally achieved when he decided to name Henry II as his successor.",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Stephen,_King_of_England",
				media : [ {
					id : 597658,
					//src : "http://upload.wikimedia.org/wikipedia/commons/2/23/Stepan_Blois.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.5436",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320890,
				ownerId : "86389",
				ownerName : "",
				title : "Henry II",
				startDate : "1154-04-01 00:00:00",
				endDate : "1189-04-01 00:00:00",
				text : "Henry II's reign was long and eventful, especially given that he ruled over not just England but much of western France. His early reign was defined by restoring lands and government damaged during the Anarchy. His marriage to Eleanor of Aquitane produced five sons and three daughters, which led to problems in his later reign. Several of his sons and his wife revolted against Henry starting in 1172, but Henry prevailed and defeated them by 1175. Two of his five sons eventually ruled England.",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Henry_II_of_England",
				media : [ {
					id : 597659,
					//src : "http://upload.wikimedia.org/wikipedia/commons/4/48/Henry_II_of_England.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.1904",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320891,
				ownerId : "86389",
				ownerName : "",
				title : "Ranulf Flambard Escapes",
				startDate : "1101-12-25 00:00:00",
				endDate : "1101-12-25 00:00:00",
				text : "Ranulf Flambard is the first known prisoner of the Tower, and is also the first to escape.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Ranulf_Flambard",
				media : [ {
					id : 597660,
					//src : "http://upload.wikimedia.org/wikipedia/commons/8/88/Westminster_Hall_edited.jpg",
					caption : "Drawing from 1800s of Westminster Hall; Flambard oversaw the construction of the walls in 1090s",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320892,
				ownerId : "86389",
				ownerName : "",
				title : "Richard I",
				startDate : "1189-04-01 00:00:00",
				endDate : "1199-04-01 00:00:00",
				text : "Also known as Richard the Lionheart",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597661,
					//src : "http://upload.wikimedia.org/wikipedia/commons/4/43/Richard_coeur_de_lion.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.4782",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320893,
				ownerId : "86389",
				ownerName : "",
				title : "John",
				startDate : "1199-04-01 00:00:00",
				endDate : "1216-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/John_of_England",
				media : [ {
					id : 597662,
					//src : "http://upload.wikimedia.org/wikipedia/commons/4/41/Jan_tomb.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320894,
				ownerId : "86389",
				ownerName : "",
				title : "Henry III",
				startDate : "1216-04-01 00:00:00",
				endDate : "1272-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Henry_III_of_England",
				media : [ {
					id : 597663,
					//src : "http://upload.wikimedia.org/wikipedia/commons/7/70/Henrytreti.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320895,
				ownerId : "86389",
				ownerName : "",
				title : "Edward I",
				startDate : "1272-04-01 00:00:00",
				endDate : "1307-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Edward_I_of_England",
				media : [ {
					id : 597664,
					//src : "http://upload.wikimedia.org/wikipedia/commons/b/ba/Eduard1_korunovace.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320896,
				ownerId : "86389",
				ownerName : "",
				title : "Edward II",
				startDate : "1307-04-01 00:00:00",
				endDate : "1327-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597665,
					//src : "http://upload.wikimedia.org/wikipedia/commons/9/96/Seal_of_Edward_II.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320897,
				ownerId : "86389",
				ownerName : "",
				title : "Edward III",
				startDate : "1327-04-01 00:00:00",
				endDate : "1377-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597666,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Edward_III_Black_Prince_14thc.jpg/416px-Edward_III_Black_Prince_14thc.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.5555",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320898,
				ownerId : "86389",
				ownerName : "",
				title : "Richard II",
				startDate : "1377-04-01 00:00:00",
				endDate : "1399-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597667,
					//src : "http://upload.wikimedia.org/wikipedia/commons/d/d1/Richard2_Anna.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320899,
				ownerId : "86389",
				ownerName : "",
				title : "Henry IV",
				startDate : "1399-04-01 00:00:00",
				endDate : "1413-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597668,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/King_Henry_IV_from_NPG_%282%29.jpg/367px-King_Henry_IV_from_NPG_%282%29.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.52",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320900,
				ownerId : "86389",
				ownerName : "",
				title : "Henry V",
				startDate : "1413-04-01 00:00:00",
				endDate : "1422-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597669,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Henry5.JPG/430px-Henry5.JPG",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.2586",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320901,
				ownerId : "86389",
				ownerName : "",
				title : "Henry VI (1st reign)",
				startDate : "1422-04-01 00:00:00",
				endDate : "1461-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597670,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/HenryVIofEngland.JPG/328px-HenryVIofEngland.JPG",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.4843",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320902,
				ownerId : "86389",
				ownerName : "",
				title : "Edward IV (1st reign)",
				startDate : "1461-04-01 00:00:00",
				endDate : "1470-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597671,
					//src : "http://upload.wikimedia.org/wikipedia/commons/4/41/EdwardIVofEngland-Yorkist.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320903,
				ownerId : "86389",
				ownerName : "",
				title : "Edward IV (2nd reign)",
				startDate : "1471-04-01 00:00:00",
				endDate : "1483-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597672,
					//src : "http://upload.wikimedia.org/wikipedia/commons/4/41/EdwardIVofEngland-Yorkist.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320904,
				ownerId : "86389",
				ownerName : "",
				title : "Edward V",
				startDate : "1483-04-09 00:00:00",
				endDate : "1483-06-25 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597673,
					//src : "http://upload.wikimedia.org/wikipedia/commons/5/53/King-edward-v.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.671",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320905,
				ownerId : "86389",
				ownerName : "",
				title : "Richard III",
				startDate : "1483-04-09 00:00:00",
				endDate : "1485-04-09 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597674,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/King_Richard_III_from_NPG.jpg/334px-King_Richard_III_from_NPG.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320906,
				ownerId : "86389",
				ownerName : "",
				title : "Henry VII",
				startDate : "1485-04-09 00:00:00",
				endDate : "1509-04-09 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597675,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/King_Henry_VII_from_NPG.jpg/368px-King_Henry_VII_from_NPG.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.2727",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320907,
				ownerId : "86389",
				ownerName : "",
				title : "Edward VI",
				startDate : "1547-04-01 00:00:00",
				endDate : "1553-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597676,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Portrait_of_Edward_VI_of_England.jpg/379px-Portrait_of_Edward_VI_of_England.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.5268",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320908,
				ownerId : "86389",
				ownerName : "",
				title : "Mary I",
				startDate : "1553-04-01 00:00:00",
				endDate : "1558-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597677,
					//src : "http://upload.wikimedia.org/wikipedia/commons/4/47/Mary_I_of_England_Mor.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320909,
				ownerId : "86389",
				ownerName : "",
				title : "Elizabeth I",
				startDate : "1558-04-01 00:00:00",
				endDate : "1603-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597678,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Elizabeth_I_Rainbow_Portrait.jpg/338px-Elizabeth_I_Rainbow_Portrait.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320910,
				ownerId : "86389",
				ownerName : "",
				title : "James II",
				startDate : "1685-04-01 00:00:00",
				endDate : "1688-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597679,
					//src : "http://upload.wikimedia.org/wikipedia/commons/9/99/James_II_by_Peter_Lely.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.5955",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320911,
				ownerId : "86389",
				ownerName : "",
				title : "James I",
				startDate : "1603-04-01 00:00:00",
				endDate : "1625-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597680,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/King_James_I_of_England_and_VI_of_Scotland_by_John_De_Critz_the_Elder.jpg/347px-King_James_I_of_England_and_VI_of_Scotland_by_John_De_Critz_the_Elder.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320912,
				ownerId : "86389",
				ownerName : "",
				title : "Charles I",
				startDate : "1625-04-01 00:00:00",
				endDate : "1649-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597681,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Charles_I_%28Daniel_Mytens%29.jpg/387px-Charles_I_%28Daniel_Mytens%29.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.4545",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320913,
				ownerId : "86389",
				ownerName : "",
				title : "LP Oliver Cromwell",
				startDate : "1653-04-01 00:00:00",
				endDate : "1658-04-01 00:00:00",
				text : "Lord Protector Oliver Cromwell of the Commonwealth",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597682,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Oliver_Cromwell_by_Robert_Walker.jpg/386px-Oliver_Cromwell_by_Robert_Walker.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.4318",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320914,
				ownerId : "86389",
				ownerName : "",
				title : "LP Richard Cromwell",
				startDate : "1658-04-01 00:00:00",
				endDate : "1659-04-01 00:00:00",
				text : "Lord Protector Richard Cromwell of the Commonwealth",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597683,
					//src : "http://upload.wikimedia.org/wikipedia/commons/7/74/RichardCromwell.jpeg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.4065",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320915,
				ownerId : "86389",
				ownerName : "",
				title : "Charles II",
				startDate : "1660-04-01 00:00:00",
				endDate : "1685-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597684,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Charles_II_%281670s%29.jpg/396px-Charles_II_%281670s%29.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.6626",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320916,
				ownerId : "86389",
				ownerName : "",
				title : "William III (Mary II)",
				startDate : "1689-04-01 00:00:00",
				endDate : "1702-04-01 00:00:00",
				text : "William III and Mary II ruled together from 1689 to Mary's death in 1694. Thereafter William III ruled alone until his death in 1702.",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [
						{
							id : 597686,
							//src : "http://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Portrait_of_William_III%2C_%281650-1702%29.jpg/382px-Portrait_of_William_III%2C_%281650-1702%29.jpg",
							caption : "",
							//type : "Image",
							thumbPosition : "0,-0.7333",
							externalMediaThumb : "",
							externalMediaType : "",
							externalMediaId : "",
							orderIndex : 1
						}, {
							id : 597685,
							//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Queen_Mary_II.jpg/398px-Queen_Mary_II.jpg",
							caption : "",
							//type : "Image",
							thumbPosition : "0,0",
							externalMediaThumb : "",
							externalMediaType : "",
							externalMediaId : "",
							orderIndex : 10
						} ]
			},
			{
				id : 1320917,
				ownerId : "86389",
				ownerName : "",
				title : "Anne",
				startDate : "1702-04-01 00:00:00",
				endDate : "1714-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597687,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Anne1705.jpg/290px-Anne1705.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320918,
				ownerId : "86389",
				ownerName : "",
				title : "George I",
				startDate : "1714-04-01 00:00:00",
				endDate : "1727-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597688,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/8/81/King_George_I_by_Sir_Godfrey_Kneller%2C_Bt.jpg/292px-King_George_I_by_Sir_Godfrey_Kneller%2C_Bt.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320919,
				ownerId : "86389",
				ownerName : "",
				title : "George II",
				startDate : "1727-04-01 00:00:00",
				endDate : "1760-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597689,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/George_II_by_Thomas_Hudson.jpg/290px-George_II_by_Thomas_Hudson.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320920,
				ownerId : "86389",
				ownerName : "",
				title : "George III",
				startDate : "1760-04-01 00:00:00",
				endDate : "1820-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597690,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/5/54/George_III_in_Coronation_edit.jpg/330px-George_III_in_Coronation_edit.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320921,
				ownerId : "86389",
				ownerName : "",
				title : "George IV",
				startDate : "1820-04-01 00:00:00",
				endDate : "1830-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597691,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/George_IV_van_het_Verenigd_Koninkrijk.jpg/347px-George_IV_van_het_Verenigd_Koninkrijk.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320922,
				ownerId : "86389",
				ownerName : "",
				title : "William IV",
				startDate : "1830-04-01 00:00:00",
				endDate : "1837-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597692,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/William_IV.jpg/314px-William_IV.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-0.2714",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320923,
				ownerId : "86389",
				ownerName : "",
				title : "Victoria",
				startDate : "1837-04-01 00:00:00",
				endDate : "1901-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597693,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Coronation_portrait_of_Queen_Victoria_-_Hayter_1838.jpg/380px-Coronation_portrait_of_Queen_Victoria_-_Hayter_1838.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320924,
				ownerId : "86389",
				ownerName : "",
				title : "Edward VII",
				startDate : "1901-04-01 00:00:00",
				endDate : "1910-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597694,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Edward_VII_in_coronation_robes.jpg/340px-Edward_VII_in_coronation_robes.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320925,
				ownerId : "86389",
				ownerName : "",
				title : "George V",
				startDate : "1910-04-01 00:00:00",
				endDate : "1936-04-01 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597695,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/George_V_of_the_united_Kingdom.jpg/341px-George_V_of_the_united_Kingdom.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320926,
				ownerId : "86389",
				ownerName : "",
				title : "Edward VIII",
				startDate : "1936-01-20 00:00:00",
				endDate : "1936-12-11 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597696,
					//src : "http://upload.wikimedia.org/wikipedia/commons/3/3b/A030596.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320927,
				ownerId : "86389",
				ownerName : "",
				title : "George VI",
				startDate : "1936-12-11 00:00:00",
				endDate : "1952-02-06 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597697,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/0/06/King_George_VI_crop.jpg/383px-King_George_VI_crop.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320928,
				ownerId : "86389",
				ownerName : "",
				title : "Elizabeth II",
				startDate : "1952-02-06 00:00:00",
				endDate : "2020-02-06 00:00:00",
				text : "Enter story info here",
				fullText : "none",
				category : "95716",
				dateFormat : "1952 - present",
				externalLink : "",
				media : [ {
					id : 597698,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Elizabeth_and_Philip_1953.jpg/411px-Elizabeth_and_Philip_1953.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320929,
				ownerId : "86389",
				ownerName : "",
				title : "War of the Roses",
				startDate : "1455-04-01 00:00:00",
				endDate : "1485-04-01 00:00:00",
				text : "The War of the Roses was a power struggle between the Houses of York and Lancaster for the English throne.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/War_of_the_roses",
				media : [ {
					id : 597699,
					//src : "http://upload.wikimedia.org/wikipedia/commons/d/d3/Siege_of_London_%28MS_1168%29.jpg",
					caption : "Siege of London, dated 1471",
					//type : "Image",
					thumbPosition : "0,-0.05",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320930,
				ownerId : "86389",
				ownerName : "",
				title : "Death of Henry VI",
				startDate : "1471-05-21 00:00:00",
				endDate : "1471-05-21 00:00:00",
				text : "Henry VI died at the Tower of London where he was imprisoned. It is suspected he was murdered.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "",
				media : []
			},
			{
				id : 1320931,
				ownerId : "86389",
				ownerName : "",
				title : "Tower Fortified",
				startDate : "1461-05-21 00:00:00",
				endDate : "1483-05-21 00:00:00",
				text : "The Tower's defenses were fortified during the War of the Roses.",
				fullText : "none",
				category : "95718",
				dateFormat : "auto",
				externalLink : "",
				media : []
			},
			{
				id : 1320932,
				ownerId : "86389",
				ownerName : "",
				title : "The Princes in the Tower Disappeared",
				startDate : "1480-05-01 00:00:00",
				endDate : "1480-05-01 00:00:00",
				text : "In one of the best-known events at the Tower of London, the two sons of Edward IV disappeared from the Tower never to be seen again.",
				fullText : "",
				category : "95717",
				dateFormat : "1483",
				externalLink : "http://en.wikipedia.org/wiki/Princes_in_the_Tower",
				media : [ {
					id : 597700,
					//src : "http://upload.wikimedia.org/wikipedia/commons/archive/c/c0/20130108125223%21Princes.jpg",
					caption : "Painting by John Everett Millais",
					//type : "Image",
					thumbPosition : "0,-0.375",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320933,
				ownerId : "86389",
				ownerName : "",
				title : "Rise of the Tudors",
				startDate : "1486-12-31 00:00:00",
				endDate : "1486-12-31 00:00:00",
				text : "Richard III was killed at the Battle of Bosworth, and the throne was claimed by Henry VII. This marked the end of the War of the Roses and the rise of the Tudors.",
				fullText : "none",
				category : "95717",
				dateFormat : "1485",
				externalLink : "http://en.wikipedia.org/wiki/House_of_Tudor",
				media : [ {
					id : 597701,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Battle_of_Bosworth_by_Philip_James_de_Loutherbourg.jpg/637px-Battle_of_Bosworth_by_Philip_James_de_Loutherbourg.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320934,
				ownerId : "86389",
				ownerName : "",
				title : "Yeoman Warders",
				startDate : "1490-12-31 00:00:00",
				endDate : "1490-12-31 00:00:00",
				text : "The Yeoman Warders (also known as Beefeaters) were formed by Henry VII to guard the Tower of London.",
				fullText : "none",
				category : "95717",
				dateFormat : "1485",
				externalLink : "http://en.wikipedia.org/wiki/Yeoman_Warder",
				media : []
			},
			{
				id : 1320935,
				ownerId : "86389",
				ownerName : "",
				title : "Lord Chancellor Thomas Becket",
				startDate : "1155-12-25 00:00:00",
				endDate : "1162-12-25 00:00:00",
				text : "Before Thomas Becket became the Archbishop of Canterbury, he was the Lord Chancellor and Keeper of Works at the Tower of London. Even though he was killed at Canterbury, his ghost is said to haunt the Tower of London.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Thomas_Becket",
				media : [ {
					id : 597702,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/English_-_Martyrdom_of_Saint_Thomas_Becket_-_Walters_W3415V_-_Open_Reverse.jpg/344px-English_-_Martyrdom_of_Saint_Thomas_Becket_-_Walters_W3415V_-_Open_Reverse.jpg",
					caption : "Illumination showing the martyrdom of Archbishop Thomas Becket - the manuscript is held by Walters Art Museum",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320936,
				ownerId : "86389",
				ownerName : "",
				title : "Defences Extended",
				startDate : "1189-12-01 00:00:00",
				endDate : "1191-10-01 00:00:00",
				text : "The defences of the Tower were extended during Richard I's reign, and work was started on the Bell tower and the Wardrobe Tower.",
				fullText : "none",
				category : "95718",
				dateFormat : "auto",
				externalLink : "",
				media : []
			},
			{
				id : 1320937,
				ownerId : "86389",
				ownerName : "",
				title : "Tower Besieged",
				startDate : "1191-10-06 00:00:00",
				endDate : "1191-10-06 00:00:00",
				text : "While Richard I was away on the Crusades, his brother John besieged the Tower of London as an attempt to claim the throne. The Tower fell in three days, but was reclaimed by Richard I on his return to England in 1194.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597703,
					//src : "http://upload.wikimedia.org/wikipedia/commons/9/91/Philippe_Auguste_et_Richard_Acre.jpg",
					caption : "Richard I and Philip II of France receive the keys to Acre whilst on Crusade",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320938,
				ownerId : "86389",
				ownerName : "",
				title : "Tower Besieged and Magna Carta Signed",
				startDate : "1215-06-15 00:00:00",
				endDate : "1215-06-15 00:00:00",
				text : "Baron Robert Fitzwalter laid siege to the Tower of London and only lifted the siege once John signed the Magna Carta.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Magna_Carta",
				media : [ {
					id : 597704,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Magna_Carta.jpg/320px-Magna_Carta.jpg",
					caption : "One of four known manuscripts, held by the British Library",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320939,
				ownerId : "86389",
				ownerName : "",
				title : "Royal Menagerie at the Tower",
				startDate : "1210-07-30 00:00:00",
				endDate : "1210-07-30 00:00:00",
				text : "The presence of lions at the Tower is first recorded. Wild and exotic animals, many of which were diplomatic gifts, lived at the Tower until the menagerie was moved to London Zoo in the 1830s.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://www.hrp.org.uk/TowerofLondon/Stories/Palacehighlights/RoyalBeasts/Menageriehistory",
				media : [ {
					id : 597705,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Wire_animals_at_tower.jpg/320px-Wire_animals_at_tower.jpg",
					caption : "Photo of wire models of animals at the Tower of London, 2011",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320940,
				ownerId : "86389",
				ownerName : "",
				title : "Two New Towers Built",
				startDate : "1216-06-15 00:00:00",
				endDate : "1238-06-15 00:00:00",
				text : "Major works took place at the Tower during Henry III's reign. This started off by building the Wakefield and Lanthorn Towers, as well as building some extensions to fortifications.",
				fullText : "none",
				category : "95718",
				dateFormat : "auto",
				externalLink : "",
				media : []
			},
			{
				id : 1320941,
				ownerId : "86389",
				ownerName : "",
				title : "Major Works",
				startDate : "1238-07-30 00:00:00",
				endDate : "1272-06-15 00:00:00",
				text : "A curtain wall was built, as were nine additional towers and a moat.",
				fullText : "none",
				category : "95718",
				dateFormat : "auto",
				externalLink : "",
				media : []
			},
			{
				id : 1320942,
				ownerId : "86389",
				ownerName : "",
				title : "Elephant Joined Menagerie",
				startDate : "1255-07-30 00:00:00",
				endDate : "1255-07-30 00:00:00",
				text : "Louis IX of France gave an African elephant to Henry III as a gift. It was added Royal Menagerie housed at the Tower.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "",
				media : []
			},
			{
				id : 1320943,
				ownerId : "86389",
				ownerName : "",
				title : "White Tower Whitewashed",
				startDate : "1240-07-30 00:00:00",
				endDate : "1240-07-30 00:00:00",
				text : "The White Tower earned its name under Henry III when it was first whitewashed. The tradition continued for many years.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597706,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Whitetowerlondon.jpg/360px-Whitetowerlondon.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320944,
				ownerId : "86389",
				ownerName : "",
				title : "Royal Mint",
				startDate : "1278-11-21 03:41:44",
				endDate : "1278-11-21 03:41:44",
				text : "The Royal Mint is moved to the Tower of London, where it was located until its 1810 move to Little Tower Hill nearby.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://www.hrp.org.uk/TowerOfLondon/stories/buildinghistory/the-royal-mint",
				media : []
			},
			{
				id : 1320945,
				ownerId : "86389",
				ownerName : "",
				title : "Defenses Further Extended",
				startDate : "1272-12-01 00:00:00",
				endDate : "1285-12-01 00:00:00",
				text : "Another curtain wall was built to enclose the existing curtain wall to form a concentric castle, and an additional moat was added. The famous Traitor's Gate was also built during this period.",
				fullText : "none",
				category : "95718",
				dateFormat : "auto",
				externalLink : "",
				media : []
			},
			{
				id : 1320946,
				ownerId : "86389",
				ownerName : "",
				title : "Margaret de Clare Imprisoned",
				startDate : "1321-11-01 00:00:00",
				endDate : "1322-11-01 00:00:00",
				text : "Margaret de Clare was the first woman imprisoned at the Tower - she was imprisoned for ordering an attack on the Queen Isabella's escort.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Margaret_de_Clare,_Baroness_Badlesmere",
				media : [ {
					id : 597707,
					//src : "http://upload.wikimedia.org/wikipedia/commons/0/05/Retour_d_Isabelle_de_France_en_Angleterre.jpg",
					caption : "Queen Isabella returning to England with her son Edward (soon to become Edward III) in 1326",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320947,
				ownerId : "86389",
				ownerName : "",
				title : "Tower Breached",
				startDate : "1381-06-13 00:00:00",
				endDate : "1381-06-13 00:00:00",
				text : "The Tower was breached during the Peasants' Revolt - the only time the Tower has been breached. Simon of Sudbury, Archbishop of Canterbury and Lord Chancellor was dragged out and killed.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Peasants%27_Revolt",
				media : [ {
					id : 597708,
					//src : "http://upload.wikimedia.org/wikipedia/commons/a/a0/Richard_II_meets_rebels.jpg",
					caption : "Richard II meets with the rebels of the Peasants' Revolt",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320948,
				ownerId : "86389",
				ownerName : "",
				title : "Tower Wharf Built",
				startDate : "1389-06-04 00:00:00",
				endDate : "1389-06-04 00:00:00",
				text : "Geoffrey Chaucer, better known as the author of Canterbury Tales, oversaw Tower Wharf being built in his role as Clerk of Works.",
				fullText : "none",
				category : "95718",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597709,
					//src : "http://upload.wikimedia.org/wikipedia/commons/0/0d/Chaucer_ellesmere.jpg",
					caption : "Illumination from Ellesmere Manuscript showing Chaucer as a pilgrim, held by Huntington Library",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320949,
				ownerId : "86389",
				ownerName : "",
				title : "Anne Boleyn Beheaded",
				startDate : "1536-05-17 00:00:00",
				endDate : "1536-05-17 00:00:00",
				text : "Anne Boleyn, the second of six wives of Henry VIII, was imprisoned in the Tower for treason, judged guilty and then beheaded.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Anne_Boleyn",
				media : [ {
					id : 597710,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Anne_boleyn.jpg/366px-Anne_boleyn.jpg",
					caption : "Anne Boleyn, late 16th century copy of original painting",
					//type : "Image",
					thumbPosition : "0,-0.7425",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320950,
				ownerId : "86389",
				ownerName : "",
				title : "Jane Grey Executed",
				startDate : "1554-02-12 00:00:00",
				endDate : "1554-02-12 00:00:00",
				text : "Edward III named Lady Jane Grey as his successor on his deathbed. She ruled from the Tower of London from 10 to 19 July 1553, when the Privy Council decided to name Mary as Queen. She was subsequently charged with treason, imprisoned in the Tower and later executed.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Lady_Jane_Grey",
				media : [ {
					id : 597711,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Streathamladyjayne.jpg/371px-Streathamladyjayne.jpg",
					caption : "Lady Jane Grey, Streatham Portrait",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320951,
				ownerId : "86389",
				ownerName : "",
				title : "Elizabeth I Imprisoned",
				startDate : "1556-03-18 00:00:00",
				endDate : "1556-03-18 00:00:00",
				text : "Elizabeth (later to become Elizabeth I) was imprisoned in the Tower by her sister Mary for treason from 18 March to 22 May 1554.",
				fullText : "none",
				category : "95717",
				dateFormat : "1554",
				externalLink : "http://en.wikipedia.org/wiki/Elizabeth_I",
				media : []
			},
			{
				id : 1320952,
				ownerId : "86389",
				ownerName : "",
				title : "St Peter ad Vincula Rebuilt",
				startDate : "1519-08-03 00:00:00",
				endDate : "1519-08-03 00:00:00",
				text : "A chapel stood on this site since before the founding of the Tower of London. It was rebuilt for Henry VIII, and housed the remains of some of those executed at the Tower.",
				fullText : "none",
				category : "95718",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/St._Peter_ad_Vincula_(London)",
				media : [ {
					id : 597712,
					//src : "http://upload.wikimedia.org/wikipedia/commons/4/4b/St-Peter-Ad-Vincula.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320953,
				ownerId : "86389",
				ownerName : "",
				title : "Gunpowder Plot",
				startDate : "1605-11-05 00:00:00",
				endDate : "1605-11-05 00:00:00",
				text : "A group of conspirators planned to blow up the House of Lords. One of the conspirators - Guy Fawkes - was captured and tortured at the Tower.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Gunpowder_Plot",
				media : [ {
					id : 597713,
					//src : "http://upload.wikimedia.org/wikipedia/commons/b/b8/GunpowderPlot.jpg",
					caption : "Broadside ballad of the plot, dating from late 17th or early 18th century",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320954,
				ownerId : "86389",
				ownerName : "",
				title : "Crown Jewels Destroyed",
				startDate : "1649-08-12 00:00:00",
				endDate : "1649-08-12 00:00:00",
				text : "Following the English Civil War, Parliament ordered the Crown Jewels held at the Tower to be destroyed, dismantled and/or sold to pay for the war. All of the current Crown Jewels date from the Restoration of 1660 and later.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "",
				media : [ {
					id : 597714,
					//src : "http://upload.wikimedia.org/wikipedia/commons/8/8e/Imperial_State_Crown2.JPG",
					caption : "Imperial State Crown",
					//type : "Image",
					thumbPosition : "0,1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320955,
				ownerId : "86389",
				ownerName : "",
				title : "Great Fire of London",
				startDate : "1666-09-04 00:00:00",
				endDate : "1666-09-04 00:00:00",
				text : "The Great Fire of London destroyed the City of London, and came close to the Tower but was stopped by a firebreak.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Fire_of_London",
				media : [ {
					id : 597715,
					//src : "http://upload.wikimedia.org/wikipedia/commons/b/b6/Great_Fire_London.jpg",
					caption : "",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320956,
				ownerId : "86389",
				ownerName : "",
				title : "Crown Jewels Almost Stolen",
				startDate : "1671-05-09 00:00:00",
				endDate : "1671-05-09 00:00:00",
				text : "Colonel Blood attempts to steal the Crown Jewels but is thwarted when discovered by the Keeper's son.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://www.hrp.org.uk/TowerOfLondon/stories/anattempttostealthecrownjewels",
				media : []
			},
			{
				id : 1320957,
				ownerId : "86389",
				ownerName : "",
				title : "Isaac Newton, Master of the Mint",
				startDate : "1699-05-09 00:00:00",
				endDate : "1727-05-09 00:00:00",
				text : "The role of Master of the Mint was traditionally a sinecure, but Sir Isaac Newton took the role quite seriously, reforming the currency and actively punishing counterfeiters.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Isaac_Newton",
				media : [ {
					id : 597716,
					//src : "http://upload.wikimedia.org/wikipedia/commons/archive/3/39/20090609182224%21GodfreyKneller-IsaacNewton-1689.jpg",
					caption : "Portrait of Sir Isaac Newton in 1689 by Sir Godfrey Kneller",
					//type : "Image",
					thumbPosition : "0,-0.475",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320958,
				ownerId : "86389",
				ownerName : "",
				title : "Last Executions on Tower Hill",
				startDate : "1780-05-09 00:00:00",
				endDate : "1780-05-09 00:00:00",
				text : "The last executions by hanging take place on Tower Hill, a 'liberty' of the Tower just north of the site.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Tower_Hill",
				media : [ {
					id : 597717,
					//src : "http://upload.wikimedia.org/wikipedia/commons/3/31/Monmouth%27s_Execution.gif",
					caption : "Execution of Monmouth in 1685 on Tower Hill",
					//type : "Image",
					thumbPosition : "0,-0.2",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320959,
				ownerId : "86389",
				ownerName : "",
				title : "Royal Menagerie Moved",
				startDate : "1835-05-09 00:00:00",
				endDate : "1835-05-09 00:00:00",
				text : "The final animals remaining at Royal Menagerie are moved to the London Zoo.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://www.hrp.org.uk/TowerofLondon/Stories/Palacehighlights/RoyalBeasts/Menageriehistory",
				media : []
			},
			{
				id : 1320960,
				ownerId : "86389",
				ownerName : "",
				title : "'Tower of London' Published",
				startDate : "1840-05-09 00:00:00",
				endDate : "1840-05-09 00:00:00",
				text : "A historical romance novel by William Harrison Ainsworth entitled 'The Tower of London' is published which colours perceptions of the Tower.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/The_Tower_of_London_(novel)",
				media : [ {
					id : 597718,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/The_Tower_of_London.jpg/282px-The_Tower_of_London.jpg",
					caption : "Title page of the novel",
					//type : "Image",
					thumbPosition : "0,0.475",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320961,
				ownerId : "86389",
				ownerName : "",
				title : "Koh-i-Noor Presented",
				startDate : "1850-05-09 00:00:00",
				endDate : "1850-05-09 00:00:00",
				text : "The Koh-i-Noor diamond is presented to Queen Victoria by Dulip Singh, and eventually is incorporated into the Queen Consort Alexandra's crown.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Koh-i-Noor",
				media : [ {
					id : 597719,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/7/71/AlexandraKohinoor.jpg/285px-AlexandraKohinoor.jpg",
					caption : "Queen Consort Alexandra wearing her coronation crown with the Koh-i-Noor in 1902",
					//type : "Image",
					thumbPosition : "0,-0.825",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320962,
				ownerId : "86389",
				ownerName : "",
				title : "Kray Twins Held",
				startDate : "1952-05-09 00:00:00",
				endDate : "1952-05-09 00:00:00",
				text : "The East-End Gangsters Ronald and Reginald Kray are among the last prisoners held at the Tower of London. They were held there briefly for attacking a constable who tried to arrest them for being absent without leave from National Service.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Kray_twins",
				media : [ {
					id : 597720,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/The_blind_beggar_1.jpg/134px-The_blind_beggar_1.jpg",
					caption : "The Blind Beggar Pub where Ronnie Kray killed a man in 1966, Photograph by Fin Fahey in 2005",
					//type : "Image",
					thumbPosition : "0,0.7",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320963,
				ownerId : "86389",
				ownerName : "",
				title : "World Heritage Site",
				startDate : "1988-05-09 00:00:00",
				endDate : "1988-05-09 00:00:00",
				text : "The Tower of London is made a World Heritage Site by UNESCO.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://whc.unesco.org/en/list/488",
				media : [ {
					id : 597721,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Tower_of_London_main_entrance%2C_2009.jpg/320px-Tower_of_London_main_entrance%2C_2009.jpg",
					caption : "Main entrance in 2009, photo taken by Patrick C, Flickr username dynamosquito",
					//type : "Image",
					thumbPosition : "0,0",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320964,
				ownerId : "86389",
				ownerName : "",
				title : "First Female Beefeater",
				startDate : "2007-05-09 00:00:00",
				endDate : "2007-05-09 00:00:00",
				text : "Moira Cameron was appointed as the first female Yeoman Warder after 22 years of service in the British Army.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Moira_Cameron",
				media : [ {
					id : 597722,
					//src : "http://upload.wikimedia.org/wikipedia/commons/a/a7/Moira_Cameron.jpg",
					caption : "Photo taken by en.wikipedia user Joshd",
					//type : "Image",
					thumbPosition : "0,-0.65",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320965,
				ownerId : "86389",
				ownerName : "",
				title : "Josef Jakobs Executed",
				startDate : "1941-08-15 00:00:00",
				endDate : "1941-08-15 00:00:00",
				text : "The last person executed at the Tower of London was Josef Jakobs, who was convicted of being a German spy during World War II.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Josef_Jakobs",
				media : []
			},
			{
				id : 1320966,
				ownerId : "86389",
				ownerName : "",
				title : "Catherine Howard Beheaded",
				startDate : "1542-02-13 00:00:00",
				endDate : "1542-02-13 00:00:00",
				text : "Henry VII's fifth wife Catherine Howard was accused of adultery and beheaded.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://www.hrp.org.uk/HamptonCourtPalace/CatherineHoward",
				media : [ {
					id : 597723,
					//src : "http://upload.wikimedia.org/wikipedia/commons/3/32/HowardCatherine02.jpeg",
					caption : "Portrait of Catherine Howard by Hans Holbein the Younger",
					//type : "Image",
					thumbPosition : "0,-1",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320967,
				ownerId : "86389",
				ownerName : "",
				title : "Thomas More Executed",
				startDate : "1531-07-06 00:00:00",
				endDate : "1531-07-06 00:00:00",
				text : "Thomas More, once a councillor to Henry VII, was executed on Tower Hill for refusing to recognise the King as Head of the Church. He was made a Catholic saint in 1935.",
				fullText : "none",
				category : "95717",
				dateFormat : "1535",
				externalLink : "http://en.wikipedia.org/wiki/Thomas_more",
				media : [ {
					id : 597724,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Hans_Holbein%2C_the_Younger_-_Sir_Thomas_More_-_Google_Art_Project.jpg/386px-Hans_Holbein%2C_the_Younger_-_Sir_Thomas_More_-_Google_Art_Project.jpg",
					caption : "Portrait of Sir Thomas More in 1527 by Hans Holbein the Younger, held by the Frick Collection",
					//type : "Image",
					thumbPosition : "0,-0.55",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320968,
				ownerId : "86389",
				ownerName : "",
				title : "Jane",
				startDate : "1553-07-10 00:00:00",
				endDate : "1553-07-19 00:00:00",
				text : "Also known as the Nine Days' Queen",
				fullText : "none",
				category : "95716",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Lady_Jane_Grey",
				media : []
			},
			{
				id : 1320969,
				ownerId : "86389",
				ownerName : "",
				title : "The Anarchy",
				startDate : "1135-04-01 00:00:00",
				endDate : "1153-04-01 00:00:00",
				text : "Since Henry I left no legitimate male heirs, a period of civil war between his nephew Stephen and his daughter Matilda broke out. Peace was ultimately reached when Stephen made Matilda's son Henry his successor.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/The_Anarchy",
				media : [ {
					id : 597725,
					//src : "http://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/BL_Royal_20_A._ii%2C_f._6v._Henry_I_%26_White_Ship.jpg/305px-BL_Royal_20_A._ii%2C_f._6v._Henry_I_%26_White_Ship.jpg",
					caption : "14th century manuscript showing Henry I and the White Ship which sunk with his son and heir",
					//type : "Image",
					thumbPosition : "0,-0.85",
					externalMediaThumb : "",
					externalMediaType : "",
					externalMediaId : "",
					orderIndex : 10
				} ]
			},
			{
				id : 1320970,
				ownerId : "86389",
				ownerName : "",
				title : "Control of Tower Sold",
				startDate : "1141-07-01 00:00:00",
				endDate : "1141-07-01 00:00:00",
				text : "The Constable of the Tower, Geoffrey de Mandeville, sold his allegiance to Matilda when she was gaining during the Anarchy, and then sold his allegiance back to Stephen a year later when Stephen was ahead. When he tried to sell allegiance back to Matilda later, Stephen had him arrested and stripped of his lands and authority.",
				fullText : "none",
				category : "95717",
				dateFormat : "auto",
				externalLink : "http://en.wikipedia.org/wiki/Geoffrey_de_Mandeville,_1st_Earl_of_Essex",
				media : []
			} ]
};